#
# Copyright IBM Corp. 2020
#
---
defaultBaseImageVersion: latest
properties:
- name: IBM_CLOUD_API_KEY
  value: ${API_KEY}
  type: secure
# This GIT Token is used to pull down scripts from a private repo for all the steps.
- name: GIT_TOKEN
  value: ${GIT_TOKEN}
  type: secure
stages:
- name: FETCH
  worker: null
  inputs:
  - type: git
    branch: master
    service: ${GIT_REPO}
  triggers:
  - type: git
    events: '{"push":true,"pull_request":false,"pull_request_closed":false}'
  properties:
  - name: SNYK_TOKEN
    type: secure
    value: ${SNYK_TOKEN}
  - name: SNYK_NOTIFY_CHANNEL
    value: '#pb-hc-jenk-test'
    type: text
  - name: WEB_HOOK_URL
    type: secure
    value: ${SLACK_WEB_HOOK}
  jobs:
  - name: FETCH_REPO
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |
      #!/bin/bash
      source <(curl -sSL "https://${GIT_TOKEN}@raw.github.ibm.com/Rohit-Mundayaliyath-Mundayadan/toolchain-test/master/Fetch/ArchiveRepo.sh")
  - name: SCAN_OSS
    type: tester
    fail_stage: false
    script: |
      #!/bin/bash
      source <(curl -sSL "https://${GIT_TOKEN}@raw.github.ibm.com/Rohit-Mundayaliyath-Mundayadan/toolchain-test/master/Scans/SnykOssScan.sh")
    test_type: customimage
    docker_image: snyk/snyk-cli:1.346.0-maven-3.5.4
- name: BUILD
  inputs:
  - type: job
    stage: FETCH
    job: FETCH_REPO
  triggers:
  - type: stage
  properties:
  - name: buildprops
    value: build.properties
    type: file
  - name: DOCKER_ROOT
    value: .
    type: text
  - name: DOCKER_FILE
    value: Dockerfile
    type: text
  - name: PIPELINE_IMAGE_URL
    value: ''
    type: text
  jobs:
  - name: BUILD_CONTAINER
    type: builder
    artifact_dir: output
    build_type: cr
    script: |-
      #!/bin/bash
      source <(curl -sSL "https://${GIT_TOKEN}@raw.github.ibm.com/Rohit-Mundayaliyath-Mundayadan/toolchain-test/master/Build/BuildContainer.sh")
    namespace: ${REGISTRY_NAMESPACE}
    image_name: ${APP_NAME}
    target:
      region_id: ${REGISTRY_REGION_ID}
      api_key: ${API_KEY}
  - name: SCAN_CONTAINER
    type: tester
    test_type: vulnerabilityadvisor
    fail_stage: false
    script: |-
      #!/bin/bash
      source <(curl -sSL "https://${GIT_TOKEN}@raw.github.ibm.com/Rohit-Mundayaliyath-Mundayadan/toolchain-test/master/Scans/DockerVulnerabilityScan.sh")
    use_image_from_build_input: true
    target:
      region_id: ${REGISTRY_REGION_ID}
      api_key: ${API_KEY}
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: BUILD_CONTAINER
  triggers:
  - type: stage
  properties:
  - name: buildprops
    value: build.properties
    type: file
  - name: CLUSTER_NAMESPACE
    value: ${PROD_CLUSTER_NAMESPACE}
    type: text
  - name: CHART_ROOT
    value: chart
    type: text
  - name: APP_URL
    value: ''
    type: text
  - name: HELM_VALUES_FILE
    value: ${HELM_VALUES_FILE}
    type: text
  jobs:
  - name: K8_HELM_DEPLOY
    type: deployer
    deploy_type: kubernetes
    target:
      region_id: ${PROD_REGION_ID}
      api_key: ${API_KEY}
      kubernetes_cluster: ${PROD_CLUSTER_NAME}
      resource_group: ${PROD_RESOURCE_GROUP}
    script: |
      #!/bin/bash
      source <(curl -sSL "https://${GIT_TOKEN}@raw.github.ibm.com/Rohit-Mundayaliyath-Mundayadan/toolchain-test/master/Deploy/HelmDeploy.sh")
  - name: HEALTH_CHECK
    type: deployer
    deploy_type: kubernetes
    target:
      region_id: ${PROD_REGION_ID}
      api_key: ${API_KEY}
      resource_group: ${PROD_RESOURCE_GROUP}
      kubernetes_cluster: ${PROD_CLUSTER_NAME}
    script: |
      #!/bin/bash
      source <(curl -sSL "https://${GIT_TOKEN}@raw.github.ibm.com/Rohit-Mundayaliyath-Mundayadan/toolchain-test/master/Deploy/HealthCheck.sh")
hooks:
- enabled: true
  label: null
  ssl_enabled: true
  url: https://devops-api.us-south.devops.cloud.ibm.com/v1/messaging/webhook/publish
