#
# Copyright IBM Corp. 2020
#

# This is a toolchain template used for setting up CI/CD process for applications 

# Note: To understand the structure of this file read https://github.com/open-toolchain/sdk/wiki/Template-File-Format
version: '2' # This has to be 2.
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  header: '![](toolchain.svg?localize)'
  icon: secure-lock-helm.svg
  required:
    - build
    - repo
    - notification
  info:
    git url: >
      "[" + $env.repository + "]" +
        "(" + $env.repository + ")"
    git branch: >
      "[" + $env.branch + "]" +
        "(" + $env.repository +
          "/tree/" + $env.branch + ")"
toolchain:
  name: >
    $env.toolchainName ? '{{toolchainName}}' :
      '<ENTER-TOOLCHAIN-NAME-HERE>'
  template:
    getting_started:
     $ref: "#/messages/template.gettingStarted"

# Set of tools to be used for this toolchain.
services:
  # We use the github whitewalker tool ( https://github.com/open-toolchain/sdk/wiki/services.md#github_integrated )
  repo:
    service_id: 'github_integrated'
    parameters:
      repo_name: ''
      repo_url: 'https://github.ibm.com/<ORG>/<REPO>'
      type: 'link'
      private_repo: false
      has_issues: false
      enable_traceability: true

  # Using the delivery pipeline for executing scripts
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{services.repo.parameters.repo_name}}'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          GIT_REPO: repo
          APP_NAME: '{{form.pipeline.parameters.app-name}}'
          REGISTRY_REGION_ID: '{{form.pipeline.parameters.registry-region}}'
          REGISTRY_NAMESPACE: '{{form.pipeline.parameters.registry-namespace}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
          PROD_RESOURCE_GROUP: '{{form.pipeline.parameters.prod-resource-group}}'
          PROD_CLUSTER_NAME: '{{form.pipeline.parameters.prod-cluster-name}}'
          PROD_CLUSTER_NAMESPACE: '{{form.pipeline.parameters.prod-cluster-namespace}}'
          SLACK_WEB_HOOK: '{{form.pipeline.parameters.slack-web-hook}}'
          GIT_TOKEN: '{{form.pipeline.parameters.git-token}}'
          SNYK_TOKEN: '{{form.pipeline.parameters.snyk-token}}'
          HELM_VALUES_FILE: '{{form.pipeline.parameters.helm-values-file}}'
        execute: true

  # Notification tool. Lets notify the pipeline events in 
  notification:
    service_id: 'slack'
    parameters:
      api_token: '{{form.pipeline.parameters.slack-web-hook}}' # Use this from the form
      channel_name: '' # Let the user select this
      team_url: 'wmwx' # Setting the watsion media and weather as default.

# Learn about the below form object:
#  https://github.com/open-toolchain/sdk/wiki/Template-Custom-UI#form
form:
  pipeline:
    schema:
      $ref: deploy.json
    parameters:
      app-name: >
        $env.appName ?
          '{{appName}}' : '{{services.repo.parameters.repo_name}}'
      prod-cluster-namespace: >
        $env.prodClusterNamespace ?
          '{{prodClusterNamespace}}' : 'development'
      registry-region: '{{registryRegion}}'
      registry-namespace: '{{registryNamespace}}'
      api-key: '{{apiKey}}'
      prod-region: '{{prodRegion}}'
      prod-resource-group: '{{prodResourceGroup}}'
      prod-cluster-name: '{{prodClusterName}}'
      slack-web-hook: '{{slackWebHook}}'
      git-token: '{{gitToken}}' # Will be reused in the slack service
      snyk-token: '{{snykToken}}'
      helm-values-file : '{{helmValuesFile}}'
