#
# Copyright IBM Corp. 2020
#

# This is a toolchain template used for seeting up CI/CD process for applications 

# Note: To understand the structure of this file read https://github.com/open-toolchain/sdk/wiki/Template-File-Format
version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  header: '![](toolchain.svg?localize)'
  icon: secure-lock-helm.svg
  required:
    - build
    - repo
  info:
    git url: >
      "[" + $env.repository + "]" +
        "(" + $env.repository + ")"
    git branch: >
      "[" + $env.branch + "]" +
        "(" + $env.repository +
          "/tree/" + $env.branch + ")"
toolchain:
  name: >
    $env.toolchainName ? '{{toolchainName}}' :
      '<ENTER-TOOLCHAIN-NAME-HERE>'
  template:
    getting_started:
     $ref: "#/messages/template.gettingStarted"
#
services:
  # We use the github whitewalker tool ( https://github.com/open-toolchain/sdk/wiki/services.md#github_integrated )
  repo:
    service_id: 'github_integrated'
    parameters:
      repo_name: '<ENTER_APP_NAME>'
      repo_url: 'https://github.ibm.com/<ORG>/<REPO>'
      type: 'Existing'
      private_repo: true
      has_issues: false
      enable_traceability: true
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{services.repo.parameters.repo_name}}'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          GIT_REPO: repo
          APP_NAME: '{{form.pipeline.parameters.app-name}}'
          REGISTRY_REGION_ID: '{{form.pipeline.parameters.registry-region}}'
          REGISTRY_NAMESPACE: '{{form.pipeline.parameters.registry-namespace}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
          PROD_RESOURCE_GROUP: '{{form.pipeline.parameters.prod-resource-group}}'
          PROD_CLUSTER_NAME: '{{form.pipeline.parameters.prod-cluster-name}}'
          PROD_CLUSTER_NAMESPACE: '{{form.pipeline.parameters.prod-cluster-namespace}}'
        execute: true
# Learn about form object:
#  https://github.com/open-toolchain/sdk/wiki/Template-Custom-UI#form
form:
  pipeline:
    schema:
      $ref: deploy.json
    parameters:
      app-name: >
        $env.appName ?
          '{{appName}}' : '{{services.repo.parameters.repo_name}}'
      prod-cluster-namespace: >
        $env.prodClusterNamespace ?
          '{{prodClusterNamespace}}' : 'dev'
      registry-region: '{{registryRegion}}'
      registry-namespace: '{{registryNamespace}}'
      api-key: '{{apiKey}}'
      prod-region: '{{prodRegion}}'
      prod-resource-group: '{{prodResourceGroup}}'
      prod-cluster-name: '{{prodClusterName}}'

